'use client'

import dynamic from 'next/dynamic'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, Flag, Gauge, Keyboard, Pause, RotateCcw, Trophy, VolumeX, X, ChevronRight, Zap, Wrench } from 'lucide-react'
import { changeTyres, createRace, drivers, formatTime, makeCircuit, requestPit, resetCar, standings, teams, tracks, tyreSpecs, type Race, type Setup, type Tyre } from '@/lib/racing'
import { circuitPoints } from '@/lib/circuits'
import { circuitVisual } from '@/lib/circuit-visuals'
const Scene=dynamic(()=>import('./scene'),{ssr:false,loading:()=> <div className="scene-loading">PREPARING THE GRID<span/></div>})
function TrackOutline({id,className='',race}:{id:number;className?:string;race?:Race}){
 const points=useMemo(()=>circuitPoints(id).map(([x,y])=>({x:Number(x.toFixed(1)),y:Number(y.toFixed(1))})),[id])
 const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),minY=Math.min(...ys),w=Math.max(...xs)-minX,h=Math.max(...ys)-minY,size=Math.max(w,h)
 const pad=Math.max(25,size*.075),viewBox=`${(minX-pad).toFixed(1)} ${(minY-pad).toFixed(1)} ${(w+pad*2).toFixed(1)} ${(h+pad*2).toFixed(1)}`
 const route=`M ${points.map(p=>`${p.x} ${p.y}`).join(' L ')} Z`,theme=circuitVisual(tracks[id].name),uid=`circuit-map-${id}`
 const start=points[0],next=points[1],startAngle=Math.atan2(next.y-start.y,next.x-start.x)*180/Math.PI+90,checkerSize=size*.019
 const markers=[points[Math.floor(points.length/3)],points[Math.floor(points.length*2/3)]]
 const terrainPattern=theme.terrain==='city'?'city':theme.terrain==='stadium'?'stadium':theme.terrain==='airfield'?'airfield':theme.terrain==='mountain'?'mountain':theme.terrain==='tropical'?'tropical':theme.terrain==='desert'||theme.terrain==='dunes'?'dry':theme.terrain==='coast'||theme.terrain==='lake'?'water':'green'
 return <svg className={`track-map ${className}`} viewBox={viewBox} aria-label={`${tracks[id].name} circuit map`} role="img" preserveAspectRatio="xMidYMid meet">
  <defs>
   <linearGradient id={`${uid}-wash`} x1="0" y1="0" x2="1" y2="1"><stop stopColor={theme.ground}/><stop offset="1" stopColor={theme.sky}/></linearGradient>
   <pattern id={`${uid}-terrain`} width={size*.15} height={size*.15} patternUnits="userSpaceOnUse">
    {terrainPattern==='city'?<><path d={`M 0 ${size*.05} H ${size*.15} M 0 ${size*.1} H ${size*.15} M ${size*.05} 0 V ${size*.15} M ${size*.1} 0 V ${size*.15}`} stroke="#d6e0dc" strokeOpacity=".12" strokeWidth={size*.002}/><rect x={size*.025} y={size*.025} width={size*.024} height={size*.02} fill="#d9ded7" fillOpacity=".14"/><rect x={size*.11} y={size*.105} width={size*.022} height={size*.02} fill="#d9ded7" fillOpacity=".12"/></>:terrainPattern==='airfield'?<><path d={`M -${size*.04} ${size*.14} L ${size*.15} -${size*.05} M -${size*.01} ${size*.17} L ${size*.18} -${size*.02} M ${size*.03} ${size*.19} L ${size*.2} ${size*.02}`} stroke="#dbe4db" strokeOpacity=".17" strokeWidth={size*.003}/><path d={`M ${size*.075} 0 V ${size*.15}`} stroke="#f2f2e5" strokeOpacity=".17" strokeWidth={size*.004} strokeDasharray={`${size*.018} ${size*.012}`}/></>:terrainPattern==='stadium'?<><path d={`M -${size*.03} ${size*.12} Q ${size*.075} -${size*.02} ${size*.18} ${size*.12} M -${size*.03} ${size*.14} Q ${size*.075} ${size*.01} ${size*.18} ${size*.14}`} fill="none" stroke="#dce3c9" strokeOpacity=".18" strokeWidth={size*.003}/><rect x={size*.04} y={size*.045} width={size*.07} height={size*.035} rx={size*.012} fill="#dbe5cb" fillOpacity=".12"/></>:terrainPattern==='mountain'?<><path d={`M -${size*.04} ${size*.14} Q ${size*.02} ${size*.09} ${size*.06} ${size*.12} T ${size*.15} ${size*.08} T ${size*.21} ${size*.11} M -${size*.04} ${size*.17} Q ${size*.02} ${size*.12} ${size*.06} ${size*.15} T ${size*.15} ${size*.11} T ${size*.21} ${size*.14}`} fill="none" stroke="#e1ead9" strokeOpacity=".2" strokeWidth={size*.002}/></>:terrainPattern==='dry'?<><path d={`M -${size*.05} ${size*.12} Q ${size*.02} ${size*.04} ${size*.09} ${size*.1} T ${size*.22} ${size*.08} M -${size*.04} ${size*.15} Q ${size*.05} ${size*.08} ${size*.12} ${size*.14} T ${size*.22} ${size*.12}`} fill="none" stroke="#f4e1b9" strokeOpacity=".17" strokeWidth={size*.002}/></>:terrainPattern==='water'?<><path d={`M 0 ${size*.04} Q ${size*.04} ${size*.02} ${size*.08} ${size*.04} T ${size*.16} ${size*.04} M 0 ${size*.105} Q ${size*.04} ${size*.085} ${size*.08} ${size*.105} T ${size*.16} ${size*.105}`} fill="none" stroke="#b7e1e5" strokeOpacity=".2" strokeWidth={size*.002}/></>:<><path d={`M -${size*.03} ${size*.12} Q ${size*.04} ${size*.03} ${size*.1} ${size*.1} T ${size*.22} ${size*.07} M -${size*.02} ${size*.17} Q ${size*.04} ${size*.08} ${size*.1} ${size*.15} T ${size*.2} ${size*.12}`} fill="none" stroke="#d6e4c5" strokeOpacity=".15" strokeWidth={size*.002}/><circle cx={size*.045} cy={size*.05} r={size*.004} fill="#d7e2ba" fillOpacity=".27"/><circle cx={size*.128} cy={size*.145} r={size*.005} fill="#d7e2ba" fillOpacity=".23"/></>}
   </pattern>
   <pattern id={`${uid}-checks`} width={checkerSize} height={checkerSize} patternUnits="userSpaceOnUse"><rect width={checkerSize/2} height={checkerSize/2} fill="#fff"/><rect x={checkerSize/2} y={checkerSize/2} width={checkerSize/2} height={checkerSize/2} fill="#fff"/></pattern>
  </defs>
  <rect x={minX-pad} y={minY-pad} width={w+pad*2} height={h+pad*2} rx={size*.022} fill={`url(#${uid}-wash)`}/>
  <rect x={minX-pad} y={minY-pad} width={w+pad*2} height={h+pad*2} rx={size*.022} fill={`url(#${uid}-terrain)`}/>
  <path d={route} fill="none" stroke="#101719" strokeOpacity=".62" strokeWidth="20" strokeLinejoin="round" strokeLinecap="round" vectorEffect="non-scaling-stroke"/>
  <path d={route} fill="none" stroke={theme.runoff} strokeOpacity=".92" strokeWidth="13" strokeLinejoin="round" strokeLinecap="round" vectorEffect="non-scaling-stroke"/>
  <path d={route} fill="none" stroke="#252b2e" strokeWidth="9" strokeLinejoin="round" strokeLinecap="round" vectorEffect="non-scaling-stroke"/>
  <path d={route} fill="none" stroke="#536064" strokeOpacity=".68" strokeWidth="5.5" strokeLinejoin="round" strokeLinecap="round" vectorEffect="non-scaling-stroke"/>
  {theme.daypart!=='day'&&<path d={route} fill="none" stroke={theme.accent} strokeOpacity=".45" strokeWidth="7" strokeLinejoin="round" strokeLinecap="round" vectorEffect="non-scaling-stroke"/>}
  <path d={route} fill="none" stroke={theme.accent} strokeOpacity={theme.daypart==='day'?'.5':'.92'} strokeWidth={theme.daypart==='day'?1:1.5} strokeDasharray={theme.daypart==='day'?'2 11':'3 8'} strokeLinejoin="round" vectorEffect="non-scaling-stroke"/>
  <g transform={`translate(${start.x} ${start.y}) rotate(${startAngle})`}><line x1={-checkerSize*.7} x2={checkerSize*.7} stroke="#101315" strokeWidth="4" vectorEffect="non-scaling-stroke"/><line x1={-checkerSize*.7} x2={checkerSize*.7} stroke={`url(#${uid}-checks)`} strokeWidth="3" vectorEffect="non-scaling-stroke"/></g>
  {markers.map((point,i)=><circle key={i} cx={point.x} cy={point.y} r={size*.009} fill={theme.accent} stroke="#111719" strokeWidth="1.4" vectorEffect="non-scaling-stroke"/>)}
  {race?race.cars.map((car,i)=><circle key={i} cx={Number(car.x.toFixed(1))} cy={Number(car.z.toFixed(1))} r={i===0?size*.012:size*.007} fill={i===0?'#fff':car.color} stroke={i===0?theme.accent:'#172024'} strokeWidth={i===0?3:2} vectorEffect="non-scaling-stroke"/>):<circle cx={start.x} cy={start.y} r={size*.012} fill={theme.accent} stroke="#111719" strokeWidth="1.7" vectorEffect="non-scaling-stroke"/>}
  <rect x={minX-pad} y={minY-pad} width={w+pad*2} height={h+pad*2} rx={size*.022} fill="none" stroke="#ffffff" strokeOpacity=".23" strokeWidth="1" vectorEffect="non-scaling-stroke"/>
 </svg>
}
const defaultSetup:Setup={track:0,driver:0,team:0,laps:3,difficulty:2,weather:'clear',trackCondition:'dry'}
export default function Game(){
 const [setup,setSetup]=useState<Setup>(defaultSetup),[race,setRace]=useState<Race|null>(null),[revision,render]=useState(0),[help,setHelp]=useState(false),[records,setRecords]=useState<Record<string,number>>({}),[loaded,setLoaded]=useState(false)
 const keys=useRef(new Set<string>())
 const updateHud=useCallback(()=>render(v=>v+1),[])
 const circuit=useMemo(()=>makeCircuit(setup.track),[setup.track])
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('apex-settings')||'null');if(stored&&Number.isInteger(stored.track)&&stored.track>=0&&stored.track<tracks.length&&[0,1,2,3].includes(stored.driver)&&[0,1,2].includes(stored.team)&&[1,3,5].includes(stored.laps)&&[0,1,2].includes(stored.difficulty))setSetup({...defaultSetup,...stored,weather:['clear','cloudy','rain','heavy-rain'].includes(stored.weather)?stored.weather:defaultSetup.weather,trackCondition:['dry','damp','wet'].includes(stored.trackCondition)?stored.trackCondition:defaultSetup.trackCondition});const savedRecords=JSON.parse(localStorage.getItem('apex-real-circuit-records-v2')||'{}');if(savedRecords&&typeof savedRecords==='object')setRecords(Object.fromEntries(Object.entries(savedRecords).filter(([key,value])=>tracks.some((_,i)=>String(i)===key)&&typeof value==='number'&&Number.isFinite(value)&&value>0)) as Record<string,number>)}catch{}setLoaded(true)},[])
 useEffect(()=>{if(loaded)try{localStorage.setItem('apex-settings',JSON.stringify(setup))}catch{}},[setup,loaded])
 useEffect(()=>{
  if(!race)return
  const down=(e:KeyboardEvent)=>{if(e.isComposing||e.keyCode===229)return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='p'){if(!e.repeat){requestPit(race);render(v=>v+1)}return}keys.current.add(k);if(e.repeat)return;if(k==='escape'){race.paused=!race.paused;keys.current.clear();render(v=>v+1)}if(k==='c')race.camera=1-race.camera;if(k==='r'&&!race.finished)resetCar(race,circuit)}
  const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase())
  const blur=()=>{keys.current.clear();race.paused=true;render(v=>v+1)}
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur)
  return ()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);keys.current.clear()}
 },[race,circuit])
 useEffect(()=>{if(!race?.finished)return;const best=race.cars[0].best;if(Number.isFinite(best)&&(!records[setup.track]||best<records[setup.track])){const next={...records,[setup.track]:best};setRecords(next);try{localStorage.setItem('apex-real-circuit-records-v2',JSON.stringify(next))}catch{}}},[race,revision,records,setup.track])
 useEffect(()=>{
  if(!help&&!race?.paused&&!race?.finished)return
  const dialog=document.querySelector<HTMLElement>('[role="dialog"]');if(!dialog)return
  const previous=document.activeElement as HTMLElement|null
  const buttons=Array.from(dialog.querySelectorAll<HTMLElement>('button, [href], select, [tabindex="0"]'))
  buttons[0]?.focus()
  const trap=(event:KeyboardEvent)=>{if(event.key==='Escape'&&help)setHelp(false);if(event.key!=='Tab'||!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
  document.addEventListener('keydown',trap)
  return()=>{document.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus()}
 },[help,race?.paused,race?.finished])
 const start=()=>{keys.current.clear();setRace(createRace(circuit,setup))}
 const change=<K extends keyof Setup>(key:K,value:Setup[K])=>setSetup(s=>({...s,[key]:value}))
 const driver=drivers[setup.driver],team=teams[setup.team],track=tracks[setup.track]
 if(race){const order=standings(race),player=race.cars[0],position=order.indexOf(player)+1;return <main className="race-screen">
  <Scene key={`${setup.track}-${setup.team}`} race={race} c={circuit} setup={setup} keys={keys.current} onUpdate={updateHud}/>
  <header className="race-header"><div className="wordmark">APEX<span> / RACING</span></div><div>{track.name.toUpperCase()} <span className="muted"> / RACE</span></div><button className="icon-button" aria-label="Pause race" onClick={()=>{race.paused=true;render(v=>v+1)}}><Pause size={18}/></button></header>
  <div className="standings"><div className="hud-label">POSITION <strong>{position}<small> / {race.cars.length}</small></strong></div>{order.map((car,i)=><div key={car.name} className={car===player?'is-player':''}><span>{i+1}</span><i style={{background:car.color}}/><span>{car.name.split(' ').at(-1)}</span><small>{car.finish?'FIN':i===0?'LEADER':`+${Math.round(Math.max(0,order[0].progress-car.progress))}m`}</small></div>)}</div>
  <div className="lap-panel"><span className="eyebrow">LAP</span><strong>{Math.min(player.lap+1,setup.laps)} <small>/ {setup.laps}</small></strong><p>RACE <b>{formatTime(race.time)}</b></p><p>BEST <b>{formatTime(player.best)}</b></p><div className="tyre-status"><i style={{background:tyreSpecs[player.tyre].color}}/> {tyreSpecs[player.tyre].label}<span>{Math.round(player.tyreWear*100)}% WORN</span></div></div>
  <div className="energy-panel"><div className="energy-heading"><Zap size={13}/><span>ENERGY STORE</span><b>{player.battery.toFixed(1)} <small>/ 4 MJ</small></b></div><div className="energy-meter"><i style={{width:`${player.battery/4*100}%`}}/></div><div className="energy-foot"><span>{(race.cars.some(other=>other!==player&&other.progress>player.progress&&other.progress-player.progress<Math.max(35,player.speed*1.15))&&player.overtakeEnergy>0)?'OVERTAKE AVAILABLE':'BRAKE TO RECHARGE'}</span><kbd>E</kbd> DEPLOY</div><div className="overtake-meter">OVERTAKE RESERVE <b>{player.overtakeEnergy.toFixed(1)} MJ</b></div></div>
  <div className="race-map"><TrackOutline id={setup.track} race={race}/></div>
  <div className="speedometer"><div className="rev-bars">{Array.from({length:16},(_,i)=><i key={i} style={{background:player.speed/85*16>i?(i>12?'#ff443e':'#dbe4db'):'#ffffff20'}}/>)}</div><div><strong>{Math.round(player.speed*3.6)}</strong><span>KM/H</span><b>{Math.max(1,Math.min(8,Math.floor(player.speed/12)+1))}<small>GEAR</small></b></div></div>
  <div className="race-bottom"><span><kbd>C</kbd> CAMERA <kbd>R</kbd> RESET <kbd>P</kbd> PIT <kbd>ESC</kbd> PAUSE</span><span>{player.pitState==='entry'?'PIT LANE ENTRY':player.pitState==='stopped'?'PIT STOP · CHOOSE TYRES':player.pitState==='exit'?'REJOINING TRACK':race.offroad?'OFF TRACK · REDUCED GRIP':`${(setup.weather??'clear').toUpperCase()} · ${Math.round(race.trackWetness*100)}% TRACK WET`}</span><button className="pit-button" disabled={player.pitState!=='track'||race.finished||race.countdown>0} onClick={()=>{requestPit(race);render(v=>v+1)}}><Wrench size={13}/>{player.pitState==='track'?'PIT NOW':player.pitState==='stopped'?`CHANGE TYRES · ${player.pitTimer.toFixed(1)}s`:'PIT IN PROGRESS'}</button></div>
  {player.pitState==='stopped'&&<div className="tyre-picker"><span className="eyebrow">PIT CREW READY · SELECT A COMPOUND</span><div>{(['soft','medium','hard'] as Tyre[]).map(t=><button key={t} className={player.tyre===t?'selected':''} onClick={()=>{changeTyres(race,t);render(v=>v+1)}}><i style={{background:tyreSpecs[t].color}}/><b>{tyreSpecs[t].label}</b><small>{Math.round(tyreSpecs[t].grip*100)}% GRIP · {Math.round(tyreSpecs[t].wear*100)}% WEAR</small></button>)}</div><p>Stop timer: {player.pitTimer.toFixed(1)}s · Fresh tyres restore grip and energy.</p></div>}
  {race.countdown>0&&!race.paused&&<div className="countdown"><div>{[0,1,2,3,4].map(i=><i key={i} className={3.5-race.countdown>i*.55?'lit':''}/>)}</div><p>LIGHTS OUT. MAKE IT COUNT.</p></div>}
  {(race.paused||race.finished)&&<div className="modal-backdrop"><section className="race-modal" role="dialog" aria-modal="true" aria-label={race.finished?'Race results':'Race paused'}><span className="eyebrow">{race.finished?'CHEQUERED FLAG':'TAKE A BREATHER'}</span><h2>{race.finished?'Race complete.':'Race paused.'}</h2>{race.finished?<><p>You finished P{position} at {track.name}.</p><div className="results">{order.map((car,i)=><div key={car.name}><b>{i+1}</b><span>{car.name}</span><small>{car.finish?formatTime(car.finish):'Still racing'}</small></div>)}</div><p>Personal best lap <b>{formatTime(player.best)}</b></p></>:<p>Your place on the grid is waiting.</p>}{!race.finished&&<button className="primary" onClick={()=>{race.paused=false;render(v=>v+1)}}>Resume race <ArrowRight size={16}/></button>}<button className={race.finished?'primary':'secondary'} onClick={start}><RotateCcw size={15}/>{race.finished?'Race again':'Restart race'}</button><button className="text-button" onClick={()=>setRace(null)}>Return to race setup</button></section></div>}
 </main>}
 return <main className="app-shell">
  <header className="topbar"><a href="/" className="wordmark" aria-label="Apex Racing home"><span className="brand-slashes">///</span> APEX<span className="brand-sub">RACING</span></a><nav aria-label="Main navigation"><span className="nav-active">RACE WEEKEND</span><button onClick={()=>setHelp(true)}>HOW TO PLAY <ArrowUpRight size={12}/></button></nav><div className="session"><i/> SOLO SESSION <span>01</span></div></header>
  <div className="page-content"><div className="page-heading"><div><div className="eyebrow"><span className="red-line"/> THE GRID IS YOURS</div><h1>Every millisecond<span> matters.</span></h1><p>Pick your circuit. Find your driver. Own the racing line.</p></div><div className="mode-badge"><Flag size={16}/><div>QUICK RACE<small>SINGLE PLAYER · 19 AI RIVALS</small></div></div></div>
  <div className="setup-layout"><section className="circuit-section"><div className="section-label"><span><b>01</b> SELECT CIRCUIT</span><small>{String(tracks.length).padStart(2,'0')} AVAILABLE</small></div><div className="track-list">{tracks.map((t,i)=><button className={`track-card ${setup.track===i?'selected':''}`} onClick={()=>change('track',i)} aria-pressed={setup.track===i} key={t.name}><div className="track-card-top"><span className={`flag flag-${t.flag}`}/><span>{t.country}</span><span className="selection-dot"/></div><div className="track-body"><div><h2 style={t.name.length>15?{fontSize:18,lineHeight:1.2}:undefined}>{t.name}</h2><p>{t.kind}</p></div><TrackOutline id={i}/></div><div className="track-meta"><span>{t.length} <small>KM</small><i/> {t.turns} <small>TURNS</small></span><span className="track-signature" title={circuitVisual(t.name).signature}>{circuitVisual(t.name).signature}<ChevronRight size={13}/></span></div></button>)}</div><div className="track-note"><span className="tiny-square"/> GPS CIRCUIT LAYOUTS · VENUE-SPECIFIC MAPS & LIGHTING</div></section>
  <section className="configuration"><div className="section-label"><span><b>02</b> BUILD YOUR GRID</span><small>YOUR RACE. YOUR RULES.</small></div>
   <div className="car-showcase"><div className="showcase-top"><span className="eyebrow">YOUR CHALLENGER</span><span className="team-code">{team.code} <i style={{background:team.color}}/></span></div><div className="car-watermark">{team.code}</div><div className="showcase-canvas"><Scene team={setup.team} number={driver.number}/></div><div className="showcase-bottom"><span>{team.name}<small>OPEN-WHEEL · RACE SPEC</small></span><span className="car-number">{String(driver.number).padStart(2,'0')}</span></div><span className="rotate-hint">DRAG TO EXPLORE <RotateCcw size={10}/></span></div>
   <div className="roster"><div className="field-heading">SELECT DRIVER <small>{String(setup.driver+1).padStart(2,'0')} / 04</small></div><div className="driver-grid">{drivers.map((d,i)=><button key={d.name} onClick={()=>change('driver',i)} aria-pressed={setup.driver===i} className={`driver-card ${setup.driver===i?'active':''}`}><span>{d.number}</span><div><small>{d.name.split(' ')[0]}</small><strong>{d.name.split(' ').slice(1).join(' ')}</strong></div><i/></button>)}</div><div className="field-heading">SELECT TEAM <small>FREE DRIVER PAIRING</small></div><div className="team-grid">{teams.map((t,i)=><button key={t.code} aria-pressed={setup.team===i} className={setup.team===i?'active':''} onClick={()=>change('team',i)}><i style={{background:t.color}}/>{['Red Bull','Ferrari','Mercedes'][i]}{setup.team===i&&<span>✓</span>}</button>)}</div></div>
  </section></div>
  <section className="race-launch"><div className="race-options"><label>RACE LENGTH<select value={setup.laps} onChange={e=>change('laps',Number(e.target.value))}><option value={1}>1 lap · Sprint</option><option value={3}>3 laps · Short race</option><option value={5}>5 laps · Grand race</option></select></label><label>AI DIFFICULTY<select value={setup.difficulty} onChange={e=>change('difficulty',Number(e.target.value))}><option value={0}>Rookie</option><option value={1}>Competitive</option><option value={2}>Expert</option></select></label><label>WEATHER<select value={setup.weather??'clear'} onChange={e=>change('weather',e.target.value as NonNullable<Setup['weather']>)}><option value="clear">Clear</option><option value="cloudy">Cloudy</option><option value="rain">Rain</option><option value="heavy-rain">Heavy rain</option></select></label><label>TRACK CONDITION<select value={setup.trackCondition??'dry'} onChange={e=>change('trackCondition',e.target.value as NonNullable<Setup['trackCondition']>)}><option value="dry">Dry</option><option value="damp">Damp</option><option value="wet">Wet</option></select></label><div className="best-record"><Trophy size={15}/><span>PERSONAL BEST<b>{formatTime(records[setup.track])}</b></span></div></div><button className="primary start-button" onClick={start}>START YOUR ENGINE <ArrowRight size={20}/></button></section>
  <footer><span><Keyboard size={14}/><kbd>W A S D</kbd> DRIVE <i/> <kbd>S / ↓</kbd> <span className="footer-brake">BRAKE</span></span><button onClick={()=>setHelp(true)}>VIEW CONTROLS <ArrowUpRight size={12}/></button><span className="unofficial">UNOFFICIAL FAN EXPERIENCE. NOT AFFILIATED WITH FORMULA 1.</span></footer><p className="mobile-notice">For the best experience, play on a desktop with a keyboard.</p>
  </div>{help&&<div className="modal-backdrop"><section className="race-modal" role="dialog" aria-modal="true" aria-label="Driving controls"><button className="close-button" aria-label="Close controls" onClick={()=>setHelp(false)}><X/></button><span className="eyebrow">BEFORE LIGHTS OUT</span><h2>Find your racing line.</h2><p>Brake before the corner, turn smoothly, then accelerate out. Stay on the tarmac to keep your grip.</p><div className="controls-list">{[['W / ↑','Accelerate'],['S / ↓','Brake'],['A D / ← →','Steer'],['Hold E','Deploy battery · brake/lift to recharge'],['P','Pit and change tyres'],['C','Switch camera'],['R','Reset to track'],['ESC','Pause / resume']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div><p className="muted">Simplified 2026-style energy rules: deploy up to 350 kW on straights and 250 kW through bends, recharge under braking or lift-off, and use a 0.5 MJ-per-lap Overtake reserve when close to a rival.</p><p className="muted">Every venue uses its real GPS-based layout and a unique 2D circuit map, with its own trackside colors and surroundings. Floodlit circuits race after dark or at twilight. Rival pace and overtakes vary each race; track grip changes with your weather and surface choices. Records stay on this device.</p><p className="muted">Circuit data: <a href="https://github.com/bacinger/f1-circuits" target="_blank" rel="noreferrer">Tomislav Bacinger · MIT license</a>. Venue scenery is an artistic recreation.</p><button className="primary" onClick={()=>setHelp(false)}>Ready to race <ArrowRight size={16}/></button></section></div>}
 </main>
}
