'use client'

import dynamic from 'next/dynamic'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, ArrowRight, Flag, Gauge, Keyboard, Pause, RotateCcw, Trophy, VolumeX, X, ChevronRight, Zap, Wrench } from 'lucide-react'
import { changeTyres, createRace, drivers, formatTime, makeCircuit, requestPit, resetCar, standings, teams, tracks, tyreSpecs, type Race, type Setup, type Tyre } from '@/lib/racing'
const Scene=dynamic(()=>import('./scene'),{ssr:false,loading:()=> <div className="scene-loading">PREPARING THE GRID<span/></div>})
function TrackOutline({id,className='',race}:{id:number;className?:string;race?:Race}){
 const c=useMemo(()=>makeCircuit(id),[id])
 const points=c.samples.filter((_,i)=>i%8===0)
 const xs=points.map(p=>p.x),zs=points.map(p=>p.z),minX=Math.min(...xs),minZ=Math.min(...zs),w=Math.max(...xs)-minX,h=Math.max(...zs)-minZ
 return <svg className={className} viewBox={`${minX-30} ${minZ-30} ${w+60} ${h+60}`} aria-label={`${tracks[id].name} circuit outline`} role="img"><polyline points={[...points,points[0]].map(p=>`${p.x},${p.z}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="2.5" vectorEffect="non-scaling-stroke" strokeLinejoin="round"/>{race?race.cars.map((car,i)=><circle key={i} cx={car.x} cy={car.z} r={Math.max(w,h)*(i===0?.024:.015)} fill={i===0?'#ff443e':'#c0c7cb'} stroke="#121419" strokeWidth="3"/>):<circle cx="0" cy="0" r={Math.max(w,h)*.025} fill="#ff443e"/>}</svg>
}
const defaultSetup:Setup={track:0,driver:0,team:0,laps:3,difficulty:2,weather:'clear',trackCondition:'dry'}
export default function Game(){
 const [setup,setSetup]=useState<Setup>(defaultSetup),[race,setRace]=useState<Race|null>(null),[revision,render]=useState(0),[help,setHelp]=useState(false),[records,setRecords]=useState<Record<string,number>>({}),[loaded,setLoaded]=useState(false)
 const keys=useRef(new Set<string>())
 const updateHud=useCallback(()=>render(v=>v+1),[])
 const circuit=useMemo(()=>makeCircuit(setup.track),[setup.track])
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('apex-settings')||'null');if(stored&&Number.isInteger(stored.track)&&stored.track>=0&&stored.track<tracks.length&&[0,1,2,3].includes(stored.driver)&&[0,1,2].includes(stored.team)&&[1,3,5].includes(stored.laps)&&[0,1,2].includes(stored.difficulty))setSetup({...defaultSetup,...stored,weather:['clear','cloudy','rain','heavy-rain'].includes(stored.weather)?stored.weather:defaultSetup.weather,trackCondition:['dry','damp','wet'].includes(stored.trackCondition)?stored.trackCondition:defaultSetup.trackCondition});const savedRecords=JSON.parse(localStorage.getItem('apex-real-circuit-records-v2')||'{}');if(savedRecords&&typeof savedRecords==='object')setRecords(Object.fromEntries(Object.entries(savedRecords).filter(([key,value])=>tracks.some((_,i)=>String(i)===key)&&typeof value==='number'&&Number.isFinite(value)&&value>0)) as Record<string,number>)}catch{}setLoaded(true)},[])
 useEffect(()=>{if(loaded)try{localStorage.setItem('apex-settings',JSON.stringify(setup))}catch{}},[setup,loaded])
 useEffect(()=>{
  if(!race)return
  const down=(e:KeyboardEvent)=>{if(e.isComposing||e.keyCode===229)return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='p'){if(!e.repeat){requestPit(race);render(v=>v+1)}return}keys.current.add(k);if(e.repeat)return;if(k==='escape'){race.paused=!race.paused;keys.current.clear();render(v=>v+1)}if(k==='c')race.camera=1-race.camera;if(k==='r'&&!race.finished)resetCar(race,circuit)}
  const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase())
  const blur=()=>{keys.current.clear();race.paused=true;render(v=>v+1)}
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur)
  return ()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);keys.current.clear()}
 },[race,circuit])
 useEffect(()=>{if(!race?.finished)return;const best=race.cars[0].best;if(Number.isFinite(best)&&(!records[setup.track]||best<records[setup.track])){const next={...records,[setup.track]:best};setRecords(next);try{localStorage.setItem('apex-real-circuit-records-v2',JSON.stringify(next))}catch{}}},[race,revision,records,setup.track])
 useEffect(()=>{
  if(!help&&!race?.paused&&!race?.finished)return
  const dialog=document.querySelector<HTMLElement>('[role="dialog"]');if(!dialog)return
  const previous=document.activeElement as HTMLElement|null
  const buttons=Array.from(dialog.querySelectorAll<HTMLElement>('button, [href], select, [tabindex="0"]'))
  buttons[0]?.focus()
  const trap=(event:KeyboardEvent)=>{if(event.key==='Escape'&&help)setHelp(false);if(event.key!=='Tab'||!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
  document.addEventListener('keydown',trap)
  return()=>{document.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus()}
 },[help,race?.paused,race?.finished])
 const start=()=>{keys.current.clear();setRace(createRace(circuit,setup))}
 const change=<K extends keyof Setup>(key:K,value:Setup[K])=>setSetup(s=>({...s,[key]:value}))
 const driver=drivers[setup.driver],team=teams[setup.team],track=tracks[setup.track]
 if(race){const order=standings(race),player=race.cars[0],position=order.indexOf(player)+1;return <main className="race-screen">
  <Scene key={`${setup.track}-${setup.team}`} race={race} c={circuit} setup={setup} keys={keys.current} onUpdate={updateHud}/>
  <header className="race-header"><div className="wordmark">APEX<span> / RACING</span></div><div>{track.name.toUpperCase()} <span className="muted"> / RACE</span></div><button className="icon-button" aria-label="Pause race" onClick={()=>{race.paused=true;render(v=>v+1)}}><Pause size={18}/></button></header>
  <div className="standings"><div className="hud-label">POSITION <strong>{position}<small> / {race.cars.length}</small></strong></div>{order.map((car,i)=><div key={car.name} className={car===player?'is-player':''}><span>{i+1}</span><i style={{background:car.color}}/><span>{car.name.split(' ').at(-1)}</span><small>{car.finish?'FIN':i===0?'LEADER':`+${Math.round(Math.max(0,order[0].progress-car.progress))}m`}</small></div>)}</div>
  <div className="lap-panel"><span className="eyebrow">LAP</span><strong>{Math.min(player.lap+1,setup.laps)} <small>/ {setup.laps}</small></strong><p>RACE <b>{formatTime(race.time)}</b></p><p>BEST <b>{formatTime(player.best)}</b></p><div className="tyre-status"><i style={{background:tyreSpecs[player.tyre].color}}/> {tyreSpecs[player.tyre].label}<span>{Math.round(player.tyreWear*100)}% WORN</span></div></div>
  <div className="energy-panel"><div className="energy-heading"><Zap size={13}/><span>ENERGY STORE</span><b>{player.battery.toFixed(1)} <small>/ 4 MJ</small></b></div><div className="energy-meter"><i style={{width:`${player.battery/4*100}%`}}/></div><div className="energy-foot"><span>{(race.cars.some(other=>other!==player&&other.progress>player.progress&&other.progress-player.progress<Math.max(35,player.speed*1.15))&&player.overtakeEnergy>0)?'OVERTAKE AVAILABLE':'BRAKE TO RECHARGE'}</span><kbd>E</kbd> DEPLOY</div><div className="overtake-meter">OVERTAKE RESERVE <b>{player.overtakeEnergy.toFixed(1)} MJ</b></div></div>
  <div className="race-map"><TrackOutline id={setup.track} race={race}/></div>
  <div className="speedometer"><div className="rev-bars">{Array.from({length:16},(_,i)=><i key={i} style={{background:player.speed/85*16>i?(i>12?'#ff443e':'#dbe4db'):'#ffffff20'}}/>)}</div><div><strong>{Math.round(player.speed*3.6)}</strong><span>KM/H</span><b>{Math.max(1,Math.min(8,Math.floor(player.speed/12)+1))}<small>GEAR</small></b></div></div>
  <div className="race-bottom"><span><kbd>C</kbd> CAMERA <kbd>R</kbd> RESET <kbd>P</kbd> PIT <kbd>ESC</kbd> PAUSE</span><span>{player.pitState==='entry'?'PIT LANE ENTRY':player.pitState==='stopped'?'PIT STOP · CHOOSE TYRES':player.pitState==='exit'?'REJOINING TRACK':race.offroad?'OFF TRACK · REDUCED GRIP':`${(setup.weather??'clear').toUpperCase()} · ${Math.round(race.trackWetness*100)}% TRACK WET`}</span><button className="pit-button" disabled={player.pitState!=='track'||race.finished||race.countdown>0} onClick={()=>{requestPit(race);render(v=>v+1)}}><Wrench size={13}/>{player.pitState==='track'?'PIT NOW':player.pitState==='stopped'?`CHANGE TYRES · ${player.pitTimer.toFixed(1)}s`:'PIT IN PROGRESS'}</button></div>
  {player.pitState==='stopped'&&<div className="tyre-picker"><span className="eyebrow">PIT CREW READY · SELECT A COMPOUND</span><div>{(['soft','medium','hard'] as Tyre[]).map(t=><button key={t} className={player.tyre===t?'selected':''} onClick={()=>{changeTyres(race,t);render(v=>v+1)}}><i style={{background:tyreSpecs[t].color}}/><b>{tyreSpecs[t].label}</b><small>{Math.round(tyreSpecs[t].grip*100)}% GRIP · {Math.round(tyreSpecs[t].wear*100)}% WEAR</small></button>)}</div><p>Stop timer: {player.pitTimer.toFixed(1)}s · Fresh tyres restore grip and energy.</p></div>}
  {race.countdown>0&&!race.paused&&<div className="countdown"><div>{[0,1,2,3,4].map(i=><i key={i} className={3.5-race.countdown>i*.55?'lit':''}/>)}</div><p>LIGHTS OUT. MAKE IT COUNT.</p></div>}
  {(race.paused||race.finished)&&<div className="modal-backdrop"><section className="race-modal" role="dialog" aria-modal="true" aria-label={race.finished?'Race results':'Race paused'}><span className="eyebrow">{race.finished?'CHEQUERED FLAG':'TAKE A BREATHER'}</span><h2>{race.finished?'Race complete.':'Race paused.'}</h2>{race.finished?<><p>You finished P{position} at {track.name}.</p><div className="results">{order.map((car,i)=><div key={car.name}><b>{i+1}</b><span>{car.name}</span><small>{car.finish?formatTime(car.finish):'Still racing'}</small></div>)}</div><p>Personal best lap <b>{formatTime(player.best)}</b></p></>:<p>Your place on the grid is waiting.</p>}{!race.finished&&<button className="primary" onClick={()=>{race.paused=false;render(v=>v+1)}}>Resume race <ArrowRight size={16}/></button>}<button className={race.finished?'primary':'secondary'} onClick={start}><RotateCcw size={15}/>{race.finished?'Race again':'Restart race'}</button><button className="text-button" onClick={()=>setRace(null)}>Return to race setup</button></section></div>}
 </main>}
 return <main className="app-shell">
  <header className="topbar"><a href="/" className="wordmark" aria-label="Apex Racing home"><span className="brand-slashes">///</span> APEX<span className="brand-sub">RACING</span></a><nav aria-label="Main navigation"><span className="nav-active">RACE WEEKEND</span><button onClick={()=>setHelp(true)}>HOW TO PLAY <ArrowUpRight size={12}/></button></nav><div className="session"><i/> SOLO SESSION <span>01</span></div></header>
  <div className="page-content"><div className="page-heading"><div><div className="eyebrow"><span className="red-line"/> THE GRID IS YOURS</div><h1>Every millisecond<span> matters.</span></h1><p>Pick your circuit. Find your driver. Own the racing line.</p></div><div className="mode-badge"><Flag size={16}/><div>QUICK RACE<small>SINGLE PLAYER · 19 AI RIVALS</small></div></div></div>
  <div className="setup-layout"><section className="circuit-section"><div className="section-label"><span><b>01</b> SELECT CIRCUIT</span><small>{String(tracks.length).padStart(2,'0')} AVAILABLE</small></div><div className="track-list">{tracks.map((t,i)=><button className={`track-card ${setup.track===i?'selected':''}`} onClick={()=>change('track',i)} aria-pressed={setup.track===i} key={t.name}><div className="track-card-top"><span className={`flag flag-${t.flag}`}/><span>{t.country}</span><span className="selection-dot"/></div><div className="track-body"><div><h2 style={t.name.length>15?{fontSize:18,lineHeight:1.2}:undefined}>{t.name}</h2><p>{t.kind}</p></div><TrackOutline id={i}/></div><div className="track-meta"><span>{t.length} <small>KM</small><i/> {t.turns} <small>TURNS</small></span><span>{i===0?'TECHNICAL':i===1?'HIGH SPEED':'BALANCED'}<ChevronRight size={13}/></span></div></button>)}</div><div className="track-note"><span className="tiny-square"/> REAL-WORLD OUTLINES · RECREATED SCENERY</div></section>
  <section className="configuration"><div className="section-label"><span><b>02</b> BUILD YOUR GRID</span><small>YOUR RACE. YOUR RULES.</small></div>
   <div className="car-showcase"><div className="showcase-top"><span className="eyebrow">YOUR CHALLENGER</span><span className="team-code">{team.code} <i style={{background:team.color}}/></span></div><div className="car-watermark">{team.code}</div><div className="showcase-canvas"><Scene team={setup.team} number={driver.number}/></div><div className="showcase-bottom"><span>{team.name}<small>OPEN-WHEEL · RACE SPEC</small></span><span className="car-number">{String(driver.number).padStart(2,'0')}</span></div><span className="rotate-hint">DRAG TO EXPLORE <RotateCcw size={10}/></span></div>
   <div className="roster"><div className="field-heading">SELECT DRIVER <small>{String(setup.driver+1).padStart(2,'0')} / 04</small></div><div className="driver-grid">{drivers.map((d,i)=><button key={d.name} onClick={()=>change('driver',i)} aria-pressed={setup.driver===i} className={`driver-card ${setup.driver===i?'active':''}`}><span>{d.number}</span><div><small>{d.name.split(' ')[0]}</small><strong>{d.name.split(' ').slice(1).join(' ')}</strong></div><i/></button>)}</div><div className="field-heading">SELECT TEAM <small>FREE DRIVER PAIRING</small></div><div className="team-grid">{teams.map((t,i)=><button key={t.code} aria-pressed={setup.team===i} className={setup.team===i?'active':''} onClick={()=>change('team',i)}><i style={{background:t.color}}/>{['Red Bull','Ferrari','Mercedes'][i]}{setup.team===i&&<span>✓</span>}</button>)}</div></div>
  </section></div>
  <section className="race-launch"><div className="race-options"><label>RACE LENGTH<select value={setup.laps} onChange={e=>change('laps',Number(e.target.value))}><option value={1}>1 lap · Sprint</option><option value={3}>3 laps · Short race</option><option value={5}>5 laps · Grand race</option></select></label><label>AI DIFFICULTY<select value={setup.difficulty} onChange={e=>change('difficulty',Number(e.target.value))}><option value={0}>Rookie</option><option value={1}>Competitive</option><option value={2}>Expert</option></select></label><label>WEATHER<select value={setup.weather??'clear'} onChange={e=>change('weather',e.target.value as NonNullable<Setup['weather']>)}><option value="clear">Clear</option><option value="cloudy">Cloudy</option><option value="rain">Rain</option><option value="heavy-rain">Heavy rain</option></select></label><label>TRACK CONDITION<select value={setup.trackCondition??'dry'} onChange={e=>change('trackCondition',e.target.value as NonNullable<Setup['trackCondition']>)}><option value="dry">Dry</option><option value="damp">Damp</option><option value="wet">Wet</option></select></label><div className="best-record"><Trophy size={15}/><span>PERSONAL BEST<b>{formatTime(records[setup.track])}</b></span></div></div><button className="primary start-button" onClick={start}>START YOUR ENGINE <ArrowRight size={20}/></button></section>
  <footer><span><Keyboard size={14}/><kbd>W A S D</kbd> DRIVE <i/> <kbd>S / ↓</kbd> <span className="footer-brake">BRAKE</span></span><button onClick={()=>setHelp(true)}>VIEW CONTROLS <ArrowUpRight size={12}/></button><span className="unofficial">UNOFFICIAL FAN EXPERIENCE. NOT AFFILIATED WITH FORMULA 1.</span></footer><p className="mobile-notice">For the best experience, play on a desktop with a keyboard.</p>
  </div>{help&&<div className="modal-backdrop"><section className="race-modal" role="dialog" aria-modal="true" aria-label="Driving controls"><button className="close-button" aria-label="Close controls" onClick={()=>setHelp(false)}><X/></button><span className="eyebrow">BEFORE LIGHTS OUT</span><h2>Find your racing line.</h2><p>Brake before the corner, turn smoothly, then accelerate out. Stay on the tarmac to keep your grip.</p><div className="controls-list">{[['W / ↑','Accelerate'],['S / ↓','Brake'],['A D / ← →','Steer'],['Hold E','Deploy battery · brake/lift to recharge'],['P','Pit and change tyres'],['C','Switch camera'],['R','Reset to track'],['ESC','Pause / resume']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</div><p className="muted">Simplified 2026-style energy rules: deploy up to 350 kW on straights and 250 kW through bends, recharge under braking or lift-off, and use a 0.5 MJ-per-lap Overtake reserve when close to a rival.</p><p className="muted">Real-world geographic outlines with simplified, flat scenery—not laser-scanned replicas. Rivals have fresh pace, form and overtaking decisions each race. Improved road grip; brake for tight corners. Records stay on this device.</p><p className="muted">Circuit data: <a href="https://github.com/bacinger/f1-circuits" target="_blank" rel="noreferrer">Tomislav Bacinger · MIT license</a>. Venue scenery is an artistic recreation.</p><button className="primary" onClick={()=>setHelp(false)}>Ready to race <ArrowRight size={16}/></button></section></div>}
 </main>
}
